### ISSUE TITLE
Simplify libevent.hpp using `decltype`

### ISSUE THREAD

**Issue by bassosimone** [bassosimone/mkok-libevent-ng#9]
The templates in src/common/libevent.hpp could be simplified (as in de-uglified, as in becoming easier to read and to maintain) using the C++11 feature `decltype` as in the following example:

``` C++
#include <sys/socket.h>

template <decltype(::recv) func = ::recv>
ssize_t Recv(int socket, void *buffer, size_t length, int flags) {
    return func(socket, buffer, length, flags);
}

int main() {
    return Recv(777, nullptr, 0, 0);
}
```

**Comment by AntonioLangiu** [comment]
:+1: I'm working on it

**Comment by bassosimone** [comment]
Excellent, thank you! With respect to the other proposed enhancement (#1) I'd say we can have a chat before you start, because I guess there few things to discuss before starting.
